# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46c134a28e12dec1a44f584d4372f99102b528a6850bf7b52009e26bd27d4147f87dca4e1ae1e1382757c484f2620231d0460a56673b88f3cd437d8ead5e00d7

test:
  secret_key_base: f54a49eabd6b3bdbf0e4bec742f358162a8d5fe0a986aaad8ddba1ebf6061bbb3bd67fcd341a6df47ef914d03f8bcd236800ec5d6a750edc56e0b5fef6d434b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
